name: firt-workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello Github Actions"
            - name: Multiline Command
              run: |
                node -v
                npm -v
parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: View macOS version
              run: sw_vers
dependent-job:
        needs: run-shell-commands
        runs-on: ubuntu-latest
        steps:
            - name: Dependent Job Step
              run: echo "This job runs after the other two jobs complete."
            - name: Error Simulation
              run: sdosdjosdjos